# Generated by Django 4.2.7 on 2025-09-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hospitaluser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'managed': False},
        ),
    ]
